$(function(){
  scrollTo(0,0)
  $('.rest').delay(1000).slideToggle(500,function(){
    $('.navbar-default').fadeIn(500)
  })
  cur=''
  $('a[href^="#"]').click(function(e){
    e.preventDefault()
    $(this).blur()
    $(cur).fadeOut()
    $(cur=$(this).attr('href')).show().scrollTop(0)
    $('html,body').animate({
      scrollTop:$($(this).attr('href')).offset().top,
      scrollLeft:$($(this).attr('href')).offset().left
    },500)
  })
  $('#s').click(function(){
    $.post('https://smhacks-molarmanful.rhcloud.com/',{email:$('#u').val()},function(x){
      $('#a').text(x).slideDown(100).addClass(x.match(/email/i)?'alert-danger':'alert-success').removeClass(x.match(/email/i)?'alert-success':'alert-danger').promise().done(function(){
        $('#a').hasClass('alert-success')&&$('#u,#s').attr('disabled','true')
				$('#a').delay(4000).slideUp(200)
      })
    })
  })
  $('.member').mouseenter(function(){
    $(this).find('.social').fadeTo(100,1)
  })
  $('.member').mouseleave(function(){
    $(this).find('.social').fadeTo(100,.01)
  })
  $('.anthony').mouseenter(function(){
    $(this).find('img').attr('src','anthony2.jpg')
  })
  $('.anthony').mouseleave(function(){
    $(this).find('img').attr('src','anthony.png')
  })
  $('.kevinf').mouseenter(function(){
    $(this).find('img').attr('src','kevinf2.jpg')
  })
  $('.kevinf').mouseleave(function(){
    $(this).find('img').attr('src','kevinf.jpg')
  })
})
